### ISSUE TITLE
Prod issue on http://pcottle.github.io/learnGitBranching/?demo

### ISSUE THREAD

**Issue by jeromeheissler** [pcottle/learnGitBranching#241]
Online demo doesn't work. An error occurs with loading of jQuery UI loaded before jQuery.

    ReferenceError: Can't find variable: jQuery

**Comment by earnaz** [comment]
Normal mode does not work

**Comment by pcottle** [comment]
Sorry about this @jeromeheissler and @earnaz! I just reordered the dependencies and removed the google CDN one since thats not available in china and pushed to prod. Should be resolved now. My bad!

**Comment by jeromeheissler** [comment]
Yeah thank you! This site is really great, I show it to my students in every course I teach.

**Comment by cartoon** [comment]
It still doesnt works for me. It looks like there is missing some css stylesheet
"NetworkError: 404 Not Found - http://pcottle.github.io/learnGitBranching/build/main.56afcf29.css"

**Comment by pcottle** [comment]
Fixed in #249 @cartoon !
